"""
Task: generate_website
Автоматическая генерация простого HTML-сайта по структуре.
"""
import os
from datetime import datetime
from core.task_registry import TaskRegistry, BaseTask
from core.config import DIRS


@TaskRegistry.register("generate_website")
class WebSiteBuilderTask(BaseTask):
    """Генерация HTML-сайта по заданной структуре (название, секции, цвета)."""

    def run(self, input_data: dict) -> dict:
        name = input_data.get("name", "My Site")
        sections = input_data.get("sections", [])
        primary = input_data.get("primary_color", "#4A3FAA")
        filename = input_data.get("filename", "index")

        nav_links = "".join(
            f'<a href="#{s["id"]}">{s["title"]}</a>'
            for s in sections if "id" in s
        )
        sections_html = ""
        for s in sections:
            sid = s.get("id", "section")
            title = s.get("title", "")
            content = s.get("content", "")
            sections_html += f"""
            <section id="{sid}">
                <h2>{title}</h2>
                <p>{content}</p>
            </section>"""

        html = f"""<!DOCTYPE html>
<html lang="ru">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{name}</title>
<style>
  *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: system-ui, sans-serif; color: #1a1a2e; background: #f8f8fc; }}
  header {{ background: {primary}; color: #fff; padding: 1.5rem 2rem; }}
  header h1 {{ font-size: 1.8rem; }}
  nav {{ background: {primary}dd; display: flex; gap: 1rem; padding: .6rem 2rem; }}
  nav a {{ color: #fff; text-decoration: none; font-size: .9rem; opacity: .85; }}
  nav a:hover {{ opacity: 1; text-decoration: underline; }}
  main {{ max-width: 860px; margin: 2rem auto; padding: 0 1.5rem; }}
  section {{ background: #fff; border-radius: 12px; padding: 1.5rem 2rem;
             margin-bottom: 1.5rem; box-shadow: 0 2px 8px rgba(0,0,0,.07); }}
  section h2 {{ color: {primary}; margin-bottom: .8rem; font-size: 1.2rem; }}
  footer {{ text-align: center; padding: 1.5rem; color: #888; font-size: .8rem; }}
</style>
</head>
<body>
<header><h1>{name}</h1></header>
<nav>{nav_links}</nav>
<main>{sections_html}</main>
<footer>Generated by AI Self-Learning System · {datetime.now().strftime("%Y-%m-%d")}</footer>
</body>
</html>"""

        out_path = os.path.join(DIRS["docs"], f"{filename}.html")
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(html)

        return {"status": "ok", "path": out_path, "filename": f"{filename}.html"}
